/// Flutter icons TracubusCustomIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TracubusCustomIcon
///      fonts:
///       - asset: fonts/TracubusCustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TracubusCustomIcon {
  TracubusCustomIcon._();

  static const _kFontFam = 'TracubusCustomIcon';
  static const String? _kFontPkg = null;

  static const IconData middle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
